--- #YAML:1.0
module_name: BSD-Getfsent
dist_version_from: lib/BSD/Getfsent.pm
installdirs: site
requires:
    Exporter: 0 
distribution_type: module
license: perl
dist_abstract: Get file system entries
