--- #YAML:1.0
name: BSD-Getfsent
version: 0.13
author:
  - Steven Philip Schubiger, <steven@accognoscere.org>
abstract: Get file system descriptor file entry
license: perl
requires:
  Exporter: 0
provides:
  BSD::Getfsent:
    file: lib/BSD/Getfsent.pm
    version: 0.13
generated_by: Module::Build version 0.2610
